-- Produkty

INSERT INTO users (login, password, is_admin) VALUES ('admin', '$2y$10$g07dJq/7Th5UDRs6Es5PHucD4OdaZUrDTSIkVWO1gnZrCY0/veuDu', true);
INSERT INTO depot (depot_id, address, capacity) VALUES (1, '3669  Arron Smith Drive', 10000);
INSERT INTO depot (depot_id, address, capacity) VALUES (2, '4757  Ingram Street', 10000);
INSERT INTO depot (depot_id, address, capacity) VALUES (3, '2779  Southern Avenue', 10000);
INSERT INTO depot (depot_id, address, capacity) VALUES (4, '1200  Spruce Drive', 10000);
INSERT INTO depot (depot_id, address, capacity) VALUES (5, '4165  James Street', 10000);
INSERT INTO depot (depot_id, address, capacity) VALUES (6, '1801  Poplar Lane', 10000);
INSERT INTO depot (depot_id, address, capacity) VALUES (7, '1677  Simons Hollow Road', 10000);
INSERT INTO depot (depot_id, address, capacity) VALUES (8, '998  Rhapsody Street', 10000);
INSERT INTO depot (depot_id, address, capacity) VALUES (9, '3527  Whiteman Street', 10000);
INSERT INTO collect_and_go (cag_id, address, capacity, used) VALUES (1, '3669  Arron Smith Drive', 25, 0); 
INSERT INTO collect_and_go (cag_id, address, capacity, used) VALUES (2, '4757  Ingram Street', 35, 0); 
INSERT INTO collect_and_go (cag_id, address, capacity, used) VALUES (3, '2779  Southern Avenue', 25, 0); 
INSERT INTO collect_and_go (cag_id, address, capacity, used) VALUES (4, '1200  Spruce Drive', 35, 0); 
INSERT INTO collect_and_go (cag_id, address, capacity, used) VALUES (5, '4165  James Street', 35, 0); 
INSERT INTO collect_and_go (cag_id, address, capacity, used) VALUES (6, '1801  Poplar Lane', 35, 0); 
INSERT INTO collect_and_go (cag_id, address, capacity, used) VALUES (7, '1677  Simons Hollow Road', 35, 0); 
INSERT INTO collect_and_go (cag_id, address, capacity, used) VALUES (8, '998  Rhapsody Stree', 25, 0); 
INSERT INTO collect_and_go (cag_id, address, capacity, used) VALUES (9, '3527  Whiteman Street', 25, 0); 
INSERT INTO collect_and_go (cag_id, address, capacity, used) VALUES (10, '3670  Arron Smith Drive', 25, 0); 
INSERT INTO collect_and_go (cag_id, address, capacity, used) VALUES (11, '4758  Ingram Street', 25, 0); 
INSERT INTO collect_and_go (cag_id, address, capacity, used) VALUES (12, '2780  Southern Avenue', 35, 0); 
INSERT INTO collect_and_go (cag_id, address, capacity, used) VALUES (13, '1201  Spruce Drive', 35, 0); 
INSERT INTO collect_and_go (cag_id, address, capacity, used) VALUES (14, '4167  James Street', 25, 0); 
INSERT INTO collect_and_go (cag_id, address, capacity, used) VALUES (15, '1802  Poplar Lane', 40, 0); 
INSERT INTO collect_and_go (cag_id, address, capacity, used) VALUES (16, '1678  Simons Hollow Road', 40, 0); 
INSERT INTO collect_and_go (cag_id, address, capacity, used) VALUES (17, '999  Rhapsody Street', 35, 0); 
INSERT INTO collect_and_go (cag_id, address, capacity, used) VALUES (18, '3528  Whiteman Street', 45, 0); 
INSERT INTO collect_and_go (cag_id, address, capacity, used) VALUES (19, '3671  Arron Smith Drive', 25, 0); 
INSERT INTO collect_and_go (cag_id, address, capacity, used) VALUES (20, '4759  Ingram Street', 25, 0); 
